services:
  portal:
    environment:
      NODE_ENV: production
    ports:
      - "${PORTAL_PORT:-3000}:3000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

  worker:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M

  postgres:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M