#!/usr/bin/env bash
# Generated by `sgit init`. Replace this with your project's real build.
#
# This runs on the CI runner after CodeSeal has decrypted the repository
# and destroyed the key material it used. Nothing here needs a secret.
set -euo pipefail

echo "TODO: build the project (e.g. cargo build / npm run build / make)"
